// shadcn/ui
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'
// shadcn/ui
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import '@/assets/css/index.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-background text-foreground font-sans antialiased',
          fontSans.variable
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  )
}
