import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import '@/assets/css/index.css'
import { cn } from '@/lib/utils'
import NavBar from '@/components/company/nav-bar'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased flex flex-col gap-y-16 sm:gap-y-20 md:gap-y-24 lg:gap-y-28 xl:gap-y-32',
          fontSans.variable
        )}
      >
        <nav className="Nav-Bar sticky top-0">
          <NavBar />
        </nav>

        <main className="Main">{children}</main>

        <footer className="Footer">CompanyMainLayout</footer>
      </body>
    </html>
  )
}
